title: Pinecone MCP Helper
description: An intelligent repository ingestion pipeline that transforms code and web content into searchable vector databases

# GitHub Pages settings
baseurl: "/pinecone-mcp-helper"
url: "https://decision-crafters.github.io"

# Build settings
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.7.0
markdown: kramdown
highlighter: rouge

# Just the Docs configuration
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025 Decision Crafters. Distributed under an MIT license."

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Enable Mermaid diagrams
mermaid:
  enable: true

# Aux links for the upper right navigation
aux_links:
  "Pinecone MCP Helper on GitHub":
    - "https://github.com/decision-crafters/pinecone-mcp-helper"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Collections
collections:
  adr:
    output: true
    permalink: /adr/:name/
