source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"
gem "jekyll-theme-cayman", "~> 0.2.0"
gem "webrick", "~> 1.8"
gem "jekyll-mermaid", "~> 1.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-seo-tag", "~> 2.8.0"
  gem "jekyll-sitemap", "~> 1.4.0"
end
