source "https://rubygems.org"

gem "jekyll", "~> 3.9.3", group: :jekyll_plugins
gem "webrick", "~> 1.8"
gem "kramdown-parser-gfm"
gem "jekyll-theme-cayman", "~> 0.2.0"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
