name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "docs-deploy"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          cd docs
          bundle update
          bundle install
          
      - name: Build with Jekyll
        run: |
          cd docs
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Deploy to docs directory in main branch
        run: |
          # Create a temporary directory for the built site
          mkdir -p /tmp/docs-site
          cp -R docs/_site/* /tmp/docs-site/
          
          # Switch to gh-pages branch or create it if it doesn't exist
          git checkout -B gh-pages
          
          # Remove old content and replace with new content
          rm -rf *
          cp -R /tmp/docs-site/* .
          
          # Add and commit changes
          git add .
          git commit -m "Update documentation site" || echo "No changes to commit"
          
          # Push changes
          git push -f origin gh-pages
